title: Charmaine Lee

logo: "/images/profile.png?raw=true" 

description: 
  <p align="center">
  # <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://linkedin.com/in/leewaiyingcharmaine">LinkedIn</a> |
  <a href="https://github.com/charmainelwy">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BS degree in Economics with a second major in Data Science at Singapore Management University.
  <br><br>
  Passionate about using data analytics and machine learning to form recommendations for business decisions, with a focus on supervised and unsupervised learning. 
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: G-G68NKL88YJ # your Google Analytics tracking ID here
