title: Charmaine Lee # your name (or website title) here
logo: "/images/profile.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>I am pursuing a Bachelors degree in Economics with a second major in Data Science at Singapore Management University.
  <br>
  <br>Passionate about using data analytics and machine learning, focusing on supervised and unsupervised learning, to form insights and recommendations to improve business decisions. 
  <a href="https://linkedin.com/in/leewaiyingcharmaine">LinkedIn</a> 
  <a href="https://github.com/charmainelwy">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-G68NKL88YJ # your Google Analytics tracking ID here
